config/routes.rb
Rails.application.routes.draw do

  #404 PG
  match "/404", to: "errors#error404", via: :all

  #500 PG
  match '/500', to: 'errors#error500', via: :all

  #SITEMAP
  get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations" }, path_names: {sign_in: "login", sign_out: "logout"}
  
  as :user do
    patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  get 'help/help_contact'

  get 'help/about'

  get 'help/terms_privacy'

  put 'help/help_contact_form'

  namespace :reps do
    devise_for :users, controllers: { registrations: "rep_registrations" },
                                        path_names: {sign_in: "login", sign_out: "logout"},
                                        only: :registrations
  end 

  devise_scope :user do
    put 'checkout' => 'registrations#checkout' 
  end 

  resources :high_schools do
    collection do
      get 'high_school'
      put 'error'
      put 'missing'
      get 'search', path: 'search'
      get 'name_or_ceeb_query_auto_complete'
      get 'city_auto_complete'
      get 'get_counties'
    end
  end
  
  resources :prospective_students do
    collection do
      get "dashboard"
      put "get_prospective_students_by_year"
      get "export"
      put "get_prospective_students_by_id"
      get "send_mail"
      get "send_test_mail"
    end
  end

  resources :users do
    get 'visits_csv' => 'users#visits_csv'
    collection do
      get 'home'
    end 

    resources :high_schools do
      collection do
        get 'all_notes' => 'notes#all_notes'
        get 'keyword_search' => 'notes#keyword_search'
      end  
      resources :notes
    end    
    resources :preferred_phones, only: [:create, :update, :destroy]
    resources :preferred_guidance_websites, only: [:create, :update, :destroy]
    resources :preferred_calendars, only: [:create, :update, :destroy]
    resources :preferred_emails, only: [:create, :update, :destroy]
    resources :saved_searches,  only: [:index,  :create, :destroy]
    resources :visits do
      put 'jsDragUpdate', as: 'drag_update'
      put 'formUpdate', as: 'form_update'
      put 'update_confirmed' => 'visits#update_confirmed'
      collection do
        get 'calendar_feed'
        get 'agenda'
        put 'share'
      end    
    end  
    resources :notes
  end 

	root 'users#home'

  namespace :admin do	   
    resources :high_schools do
      collection do
        post 'import_for_new'
        post 'import_for_update'
        get 'export'
        get 'import_template'
        get 'dashboard'
        get 'search'
      end
    end  
  end

  resources :admin do
    collection do
      resources :admins, controller: 'admin/admins', except: [:show]
    end
  end    
  
  resources :admin do
    collection do
      resources :accounts, controller: 'admin/accounts'
    end  
  end    

  resources :institutions, only: [:none] do 
    collection do
      get 'institution_auto_complete'
      get 'institution'
    end
  end    

  resources :accounts do
    collection do
      get 'credit_card_form'
    end
  end
  
end

app/controllers/admin/high_schools_controller.rb
class Admin::HighSchoolsController < ApplicationController

  include DeviseHelper
  include HighSchoolsHelper
  before_filter :authenticate_user! && :authenticate_admin


  def dashboard
    @user = current_user
    @accounts = Account.paginate(:page => params[:page], :per_page => 20)
    @users = User.where("role = 0")
  end

  def export 
    # @high_schools = HighSchool.select('name,county,address,city,state_abbreviation,zip_code,ceeb,hs_phone_num,guidance_phone_num,guidance_phone_num_ext,website,guidance_url,calendar_url,latitude,longitude,hs_type,classification,students_count,seniors_count,percent_female,percent_male,percent_asian_am,percent_african_am,percent_white,percent_hispanic_am,percent_other,reduced_lunch,four_year_school,magnet,charter,capstone,boarding,intl_bacc,sat_total,sat_math,sat_reading,sat_writing,act,median_income,religion,graduation_rate,repsedge_id')
    respond_to do |format|
      # @high_schools.to_csv
      format.csv { send_file "app/views/admin/high_schools/export.csv" }
    end
  end

  def import_template
    respond_to do |format|
      format.csv { send_data HighSchool.csvTemplate }
    end
  end

  def import_for_new
    if params[:file]
      if params[:file].content_type == "text/csv"
        if HighSchool.import_for_new(params[:file])
          redirect_to dashboard_admin_high_schools_path, notice: "New High Schools have been successfully added."
        else
          redirect_to dashboard_admin_high_schools_path, notice: "Please ensure that the file you have selected is properly formatted and try again. TIP: Download CSV Template below."
        end  
      else
        redirect_to dashboard_admin_high_schools_path, notice: "Please ensure that the file you have selected in the proper format (.csv) and try again."
      end
    else
      @user = current_user
      @accounts = Account.paginate(:page => params[:page], :per_page => 20)
      @users = User.where("role = 0")
      redirect_to dashboard_admin_high_schools_path, notice: "You must select a file to upload."
    end
  end

  # def import_for_update
  #   if params[:file] 
  #     HighSchool.import_for_update(params[:file])
  #     redirect_to dashboard_admin_high_schools_path, notice: "High Schools have been successfully updated."
  #   else
  #     render dashboard_admin_high_schools_path, notice: "You must select a to upload."
  #   end
  # end

  def search
    @states = State::ALL_STATES
  end

  def show
		@high_school = HighSchool.find(params[:id])
 	end	

 	def new
    @high_school = HighSchool.new
    @user = current_user
    @states = State::ALL_STATES
	end

	def edit
  	@high_school = HighSchool.find(params[:id])
    @states = State::ALL_STATES
	end

	def create    
    @high_school = HighSchool.new(high_school_attrs(high_school_params))
    if @high_school.save
      @high_school.update_attributes({state_abbreviation: @high_school.state.abbreviation})
      redirect_to dashboard_admin_high_schools_path, notice: "#{@high_school.name} was successfully created."
    else
      @user = current_user
      @states = State::ALL_STATES
      render action: "new", notice: @high_school.errors.full_messages
    end
	end

	def update
    @high_school = HighSchool.find(params[:id])
    @states = State::ALL_STATES
    @high_school.update(high_school_attrs(high_school_params))
    if @high_school.save
      @high_school.update_attributes({state_abbreviation: @high_school.state.abbreviation})
      redirect_to dashboard_admin_high_schools_path, notice: "#{@high_school.name} was successfully updated."
    else
      render action: "edit", notice: @high_school.errors.full_messages
    end
	end

	def destroy
    @user = current_user
    @accounts = Account.paginate(:page => params[:page], :per_page => 20)
    @users = User.where("role = 0")
    @high_school = HighSchool.find(params[:id])
    if @high_school.destroy
      render action: "dashboard", notice: "#{@high_school.name} was successfully deleted."
		end
	end

	private

  def authenticate_admin
    if current_user && current_user.account_admin?
      return
    else
      redirect_to root_path
    end    
  end

	def high_school_params
	  params.permit( :utf8, :_method, :authenticity_token, :commit, :id, :state, :county, high_school: [ :id, :name, :ceeb, :city, :state, :county, :address, :zip_code, :latitude, :longitude, :hs_phone_num, :guidance_phone_num, :website, :calendar_url, :hs_type, :classification, :religion, :address, :students_count, :seniors_count, :percent_male, :percent_female, :percent_asian_am, :percent_african_am, :percent_white, :percent_hispanic_am, :percent_other, :reduced_lunch, :four_year_school, :magnet, :charter, :capstone, :intl_bacc, :boarding, :sat_total, :sat_math, :sat_reading, :sat_writing, :act, :median_income, :created_at, :updated_at, :religion, :graduation_rate, :guidance_url, :state_id, :guidance_phone_num_ext, :repsedge_id ])
  end

  def high_school_attrs(high_school_params)
    high_school_attrs = high_school_params.clone
    high_school_attrs[:high_school][:state_id] = (State.find_by(abbreviation: high_school_params[:state])).id
    high_school_attrs[:high_school][:county] = high_school_params[:county]
    high_school_attrs[:high_school][:repsedge_id] = HighSchool.last.repsedge_id + 1
    return high_school_attrs[:high_school]
  end
end

app/helpers/high_schools_helper.rb
module HighSchoolsHelper 		

	def convertRangeStringToRangeObject(string)
		rangeArray = string.split('..').map { |e| e.to_i }
		range = Range.new(rangeArray[0], rangeArray[1])
		return range
	end	

	def genderConverter(string)
		if string == "All Male"
			return 100
		elsif string == "All Female"
			return 0
		else
			return (0..100)	
		end			
	end	

	def gradRateConverter
		self.graduation_rate == 0.0 ? "N/A" : "#{self.graduation_rate.round}%"
	end	

	def incomeRounder(string)
		if string.blank? || string == "not available" || string == "0"
			return "N/A"
		elsif string.length < 4
			return string
		elsif string.length == 4
			return string[0..1].insert(1, ".")+"k"
		else
			return string.chop.chop.chop + "k"
		end
	end	

	def generateResultsString(high_school_params)	
		resultsStringArray = []
		if high_school_params[:hs_type] && high_school_params[:hs_type] != "ALL"
			resultsStringArray.push("Type")
		end
		
		if high_school_params[:classification] && high_school_params[:classification] != "ALL"
			resultsStringArray.push("Classification")
		end

		if high_school_params[:capstone] && high_school_params[:capstone] != "false"
			resultsStringArray.push("Capstone")
		end	

		if high_school_params[:intl_bacc] && high_school_params[:intl_bacc] != "false"
			resultsStringArray.push("Int'l Bacc")
		end	

		if high_school_params[:boarding] && high_school_params[:boarding] != "false"
			resultsStringArray.push("Boarding")
		end	

		if high_school_params[:magnet] && high_school_params[:magnet] != "false"
			resultsStringArray.push("Magnet")
		end	

		if high_school_params[:charter] && high_school_params[:charter] != "false"
			resultsStringArray.push("Charter")
		end	

		if high_school_params[:religion] && high_school_params[:religion] != "ALL"
			resultsStringArray.push("Religion")
		end

		if high_school_params[:students_count] && high_school_params[:students_count] != (0..50000)
			resultsStringArray.push("Number of Students")
		end

		if high_school_params[:percent_male] && high_school_params[:percent_male] != "ALL"
			resultsStringArray.push("Gender")
		end	

		if high_school_params[:percent_white] && high_school_params[:percent_white] != (0..100)
			resultsStringArray.push("Diversity")
		end

		if high_school_params[:graduation_rate] && high_school_params[:graduation_rate] != (0..100)
			resultsStringArray.push("Graduation Rate")
		end

		if high_school_params[:median_income] && high_school_params[:median_income] != (0..9999999)
			resultsStringArray.push("Income")
		end

		if high_school_params[:reduced_lunch] && high_school_params[:reduced_lunch] != (0..100)
			resultsStringArray.push("% Free/Reduced Lunch")
		end

		if high_school_params[:act] && high_school_params[:act] != (0..36)
			resultsStringArray.push("ACT")
		end

		if high_school_params[:sat_total] && high_school_params[:sat_total] != (0..2400)
			resultsStringArray.push("SAT")
		end

		resultsString = resultsStringArray.join(", ")
		return resultsString
	end

	def convertDiversity( int )
		if int.blank?
			return "no data"
		else		
			if int > 60
				return "Less Diverse"
			elsif (int < 60) && (int > 20)
				return "Somewhat Diverse"
			else
				return "Diverse"
			end	
		end	
	end	

	def all_features_blank?
        return true unless magnet || charter || capstone || intl_bacc || boarding
    end
	
end	

app/views/admin/high_schools/_name_or_ceeb_search.html.erb
<div id="home-search-container">
	<div class="name-or-ceeb-container">

		<div id="admin-name-or-ceeb-filter">
			<%= text_field_tag "high_school[name_or_ceeb_query]", params[:high_school] && params[:high_school]["name_or_ceeb_query"],
					{ autocomplete: "off",
						id: "admin-name-search",
					  placeholder: 'ENTER HS NAME OR CEEB'} %>
		</div>
	</div>
</div>

app/views/admin/high_schools/_search.html.erb
<div class="home-search-container">
	<div id="admin-high-school-search">
		<h3>Edit Existing High School</h3>
	  	<label>Search by Name or CEEB</label>

	  <div id="search-name-ceeb">
	    <%= form_tag( high_schools_path, method: :get, class: "name-or-ceeb-search-form") do %>
	      <%= render(partial: 'admin/high_schools/name_or_ceeb_search',locals: { states: @states }) %>
	    <% end %>
	  </div>
	
	</div>
</div>

app/views/admin/high_schools/dashboard.html.erb
<div class="home-header">
  <h1>Admin Panel</h1>
  <h2>Welcome back <strong><%= @user.first_name %></strong>!</h2>
</div>

<div id="admin-tabs" class="account-manager container admin">
  <ul>
    <li><a id="high-schools-tab" href="#high-schools">High Schools</a></li>
    <li><a id="accounts-tab" href="#accounts">Accounts</a></li>
    <li><a id="admins-tab" href="#admins">Administrators</a></li>
  </ul>

  <div id="high-schools" class="col-md-12">
    <div class="admin-high-school-container">

      <div class="admin-add-high-school-container col-md-6 col-sm-6">
        <h3>Add a New High School</h3>  
        <%= link_to "<button>Add a School</button>".html_safe, new_admin_high_school_path %>
      </div>  
      <div class="admin-edit-high-school-container col-md-6 col-sm-6">
        <%= render(partial: 'admin/high_schools/search',locals: { states: @states }) %>
      </div>  
            
 
      <div class="admin-new-high-school-import-container col-md-6 col-sm-6">
        <h3>Add New High Schools</h3>  
        <%= link_to "Download CSV Template", '/admin/high_schools/import_template.csv' %>
        <%= form_tag import_for_new_admin_high_schools_path, multipart: true do %>
          <%= label_tag :file, "Import New High Schools via CSV" %>
          <%= file_field_tag :file %>
          <%= link_to "<button type='submit'>Add Schools</button>".html_safe %>
        <% end %>
      </div>  

<!--  <div class="admin-update-high-school-import-container col-md-6 col-sm-6">
        <h3>Update Existing High Schools</h3>  
        <%# form_tag import_for_update_admin_high_schools_path, multipart: true do %>
          <%# label_tag :file, "Update High Schools via CSV" %>
          <%# file_field_tag :file %>
          <%# submit_tag "Update Exisiting Schools" %>
        <%# end %>
      </div>  --> 
      
      <div class="admin-download-high-school-container col-md-6 col-sm-6">
          <h3>Download High Schools</h3>
          <%# link_to "<button>Excel</button>".html_safe, '/admin/high_schools/export.xls' %>
          <%= link_to "<button>CSV</button>".html_safe, '/admin/high_schools/export.csv' %>
      </div> 

    </div>
  </div>

  <div id="accounts">
    <div class="admin-add-account-container col-md-6 col-sm-6">
      <h3>Accounts</h3>  
    </div>

    <div class="col-md-6 col-sm-6">
      <%= link_to "<button>Create an Account</button>".html_safe, new_account_path %>
    </div>

    <br>
    <div class="col-md-12">
      <%= render(partial: "admin/accounts/all_accounts", locals: { users: @users } ) %>

      

    </div>
  </div>

  <div id="admins">
    <div class="admin-add-account-container col-md-6 col-sm-6">
      <h3>Admin</h3>
    </div>
    
    <div class="col-md-6 col-sm-6">
      <%= link_to "<button>Add a New Administrator</button>".html_safe, new_admin_path %>
    </div>
    <br>

    <div class="col-md-12">
      <%= render(partial: "admin/admins/all_admins", locals: { users: @users } ) %>
    </div>

  </div>

</div> 

app/views/admin/high_schools/edit.html.erb
<div class="home-header">
	<h1>Edit</h1> 
	<h2><%= @high_school.name %></h2>
</div>

<% if @high_school && @high_school.errors %>
	<% @high_school.errors.full_messages.each do |msg| %>
		<p class="webflash"><%=msg%></p>
	<% end %>
<% end %>
<%= render(partial: 'admin/high_schools/form',locals: { high_school: @high_school}) %>

<%= link_to("Delete this School?", 
						"/admin/high_schools/#{@high_school.id}", 
						method: :delete,
						data: {confirm: "Deleting a high school will also destroy all related content for all users, i.e. notes, visits, preferred contacts, etc. This action cannot be undone. Are you sure you want to delete this school?"})%> 

app/views/admin/high_schools/export.xls.erb
<table class="table-striped">	
	<thead>
		<tr>
			<th>name</th>
			<th>county</th>
			<th>address</th>
			<th>city</th>
			<th>state_abbreviation</th>
			<th>zip_code</th>
			<th>ceeb</th>
			<th>hs_phone_num</th>
			<th>guidance_phone_num</th>
			<th>website</th>
			<th>calendar_url</th>
			<th>latitude</th>
			<th>longitude</th>
			<th>hs_type</th>
			<th>classification</th>
			<th>students_count</th>
			<th>seniors_count</th>
			<th>percent_male</th>
			<th>percent_female</th>
			<th>percent_asian_am</th>
			<th>percent_african_am</th>
			<th>percent_white</th>
			<th>percent_hispanic_am</th>
			<th>percent_other</th>
			<th>reduced_lunch</th>
			<th>four_year_school</th>
			<th>magnet</th>
			<th>charter</th>
			<th>capstone</th>
			<th>intl_bacc</th>
			<th>boarding</th>
			<th>sat_total</th>
			<th>sat_math</th>
			<th>sat_reading</th>
			<th>sat_writing</th>
			<th>act</th>
			<th>median_income</th>
			<th>created_at</th>
			<th>updated_at</th>
			<th>religion</th>
			<th>graduation_rate</th>
			<th>guidance_url</th>
			<th>state_id</th>
			<th>guidance_phone_num_ext</th>
			<th>repsedge_id</th>
		</tr>
	</thead>
	<tbody>
		<% @high_schools.each do |high_school| %>
			<tr>
				<td>high_school.name</td>
				<td>high_school.county</td>
				<td>high_school.address</td>
				<td>high_school.city</td>
				<td>high_school.state_abbreviation</td>
				<td>high_school.zip_code</td>
				<td>high_school.ceeb</td>
				<td>high_school.hs_phone_num</td>
				<td>high_school.guidance_phone_num</td>
				<td>high_school.website</td>
				<td>high_school.calendar_url</td>
				<td>high_school.latitude</td>
				<td>high_school.longitude</td>
				<td>high_school.hs_type</td>
				<td>high_school.classification</td>
				<td>high_school.students_count</td>
				<td>high_school.seniors_count</td>
				<td>high_school.percent_male</td>
				<td>high_school.percent_female</td>
				<td>high_school.percent_asian_am</td>
				<td>high_school.percent_african_am</td>
				<td>high_school.percent_white</td>
				<td>high_school.percent_hispanic_am</td>
				<td>high_school.percent_other</td>
				<td>high_school.reduced_lunch</td>
				<td>high_school.four_year_school</td>
				<td>high_school.magnet</td>
				<td>high_school.charter</td>
				<td>high_school.capstone</td>
				<td>high_school.intl_bacc</td>
				<td>high_school.boarding</td>
				<td>high_school.sat_total</td>
				<td>high_school.sat_math</td>
				<td>high_school.sat_reading</td>
				<td>high_school.sat_writing</td>
				<td>high_school.act</td>
				<td>high_school.median_income</td>
				<td>high_school.created_at</td>
				<td>high_school.updated_at</td>
				<td>high_school.religion</td>
				<td>high_school.graduation_rate</td>
				<td>high_school.guidance_url</td>
				<td>high_school.state_id</td>
				<td>high_school.guidance_phone_num_ext</td>
				<td>high_school.repsedge_id</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/high_schools/new.html.erb
<% if @high_school && @high_school.errors %>
	<% @high_school.errors.full_messages.each do |msg| %>
		<p class="webflash"><%=msg%></p>
	<% end %>
<% end %>
<%= render(partial: 'admin/high_schools/form',locals: { high_school: @high_school}) %>