config/routes.rb
Rails.application.routes.draw do

  #404 PG
  match "/404", to: "errors#error404", via: :all

  #500 PG
  match '/500', to: 'errors#error500', via: :all

  #SITEMAP
  get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations" }, path_names: {sign_in: "login", sign_out: "logout"}
  
  as :user do
    patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  get 'help/help_contact'

  get 'help/about'

  get 'help/terms_privacy'

  put 'help/help_contact_form'

  namespace :reps do
    devise_for :users, controllers: { registrations: "rep_registrations" },
                                        path_names: {sign_in: "login", sign_out: "logout"},
                                        only: :registrations
  end 

  devise_scope :user do
    put 'checkout' => 'registrations#checkout' 
  end 

  resources :high_schools do
    collection do
      get 'high_school'
      put 'error'
      put 'missing'
      get 'search', path: 'search'
      get 'name_or_ceeb_query_auto_complete'
      get 'city_auto_complete'
      get 'get_counties'
    end
  end
  
  resources :prospective_students do
    collection do
      get "dashboard"
      put "get_prospective_students_by_year"
      get "export"
      put "get_prospective_students_by_id"
      get "send_mail"
      get "send_test_mail"
    end
  end

  resources :users do
    get 'visits_csv' => 'users#visits_csv'
    collection do
      get 'home'
    end 

    resources :high_schools do
      collection do
        get 'all_notes' => 'notes#all_notes'
        get 'keyword_search' => 'notes#keyword_search'
      end  
      resources :notes
    end    
    resources :preferred_phones, only: [:create, :update, :destroy]
    resources :preferred_guidance_websites, only: [:create, :update, :destroy]
    resources :preferred_calendars, only: [:create, :update, :destroy]
    resources :preferred_emails, only: [:create, :update, :destroy]
    resources :saved_searches,  only: [:index,  :create, :destroy]
    resources :visits do
      put 'jsDragUpdate', as: 'drag_update'
      put 'formUpdate', as: 'form_update'
      put 'update_confirmed' => 'visits#update_confirmed'
      collection do
        get 'calendar_feed'
        get 'agenda'
        put 'share'
      end    
    end  
    resources :notes
  end 

	root 'users#home'

  namespace :admin do	   
    resources :high_schools do
      collection do
        post 'import_for_new'
        post 'import_for_update'
        get 'export'
        get 'import_template'
        get 'dashboard'
        get 'search'
      end
    end  
  end

  resources :admin do
    collection do
      resources :admins, controller: 'admin/admins', except: [:show]
    end
  end    
  
  resources :admin do
    collection do
      resources :accounts, controller: 'admin/accounts'
    end  
  end    

  resources :institutions, only: [:none] do 
    collection do
      get 'institution_auto_complete'
      get 'institution'
    end
  end    

  resources :accounts do
    collection do
      get 'credit_card_form'
    end
  end
  
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :high_school
	belongs_to :user
	before_create :set_time_tag_to_now


	validates_presence_of :content



# Solr indexing
	searchable auto_index: true, auto_remove: true do
		integer :user, :stored => true do
      user.id
   	end
		text :high_school, :stored => true do
      high_school.name
   	end
		text :content, :stored => true
	end

	def self.searchNotes(keyword, user)
		search = Sunspot.search(self) do
			with(:user, user.id)
			fulltext keyword do
				highlight :content
				highlight :high_school
			end	
		end	
	end 

  def set_time_tag_to_now
    self.time_tag = Time.now unless self.time_tag.present?
  end


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_filter :authenticate_user!

	def all_notes
		@user = User.find params[:user_id]
		@notes = @user.notes.order(created_at: :desc).paginate(:page => params[:page], :per_page => 20)
	end

	def index
		@user = User.find(params[:user_id])
		@high_school = HighSchool.find(params[:high_school_id])
		@notes = @user.notes.all.where("high_school_id = #{@high_school.id}").order(created_at: :desc).limit(5)
	end

	def create
		@high_school = HighSchool.find(params[:note][:high_school_id])
		@user = User.find params[:user_id]
		@note = Note.new(note_params)
		if @note.save
			# redirect_to @high_school
			flash[:notes_success] = "Your note on #{@high_school.name} has been added."
			respond_to do |format|
		  	format.js {render inline: "location.reload()" }
			end
		else
			flash[:notes_error] = @note.errors.full_messages[0]
			redirect_to @high_school
		end	
	end

	def update
		@user = User.find(params[:user_id])
		@note = Note.find(params[:id])
		@high_school = @note.high_school
		if @note.update(note_params)
			flash[:notes_success] = "Your note on #{@high_school.name} has been updated."
			redirect_to all_notes_user_high_schools_path
		else
			flash[:notes_success] = "Your note must have content to be updated."
			redirect_to @high_school
		end	
	end	

	def destroy
	  @note = Note.find(params[:id])
	  if @note.destroy
			@user = User.find(params[:user_id])
			@notes = @user.notes
			flash[:deleted] = "Your note has been deleted."
  		respond_to do |format|
		  	format.js {render inline: "location.reload()" }
			end
		end	
	end

	def keyword_search
		search = Note.searchNotes(params[:keyword_query], current_user)
		@user = current_user
		if search.results.blank?
	  	flash[:search] = "The search parameters you selected yielded no results. Please modify your search and try again."
		else
			@search = search
	  end
	end

private

	def note_params
	  params.require(:note).permit(:user_id, :content, :time_tag, :high_school_id)
	end

end

app/views/notes/_form.html.erb
<%if flash && flash[:notes_error] %>
	<div class="webflash">	
			<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<p><%=flash[:notes_error]%></p>
	</div>
<% end %>

<% if @high_school %>
	<%= form_for [@user, @note], remote: true do |f| %>
		<div class="notes-message">
			<%= render(partial: 'notes/messages',locals: {message: @message}) %>
		</div>
		<%= f.text_area :content, 
				{ placeholder: 'Take notes here...',
				id: "note_content-field" } %>	
		<%= f.hidden_field :high_school_id, value: @high_school.id %>
		<%= f.hidden_field :user_id, value: @user.id %>
		<div class="button-container">
			<%= f.submit "SAVE", { class: "button save" }	%>
		</div>	
	<% end %>	
<% end %>	

app/views/notes/_high_school_index.html.erb
<% if @notes.blank? %>
	<p>You have no notes for this school.</p>
<% else %>
	<% @notes.reverse_each do |note| %>
    <div class="note-container">

			<%= link_to raw("<i class=\"glyphicon glyphicon-remove\"></i>"), 
							user_note_path(user.id, note.id),
							method: :delete,
							data: { confirm: "Delete this note?" },
							remote: true,
							class: 'close' %>
			<%= link_to user_high_school_notes_path(@user.id, @high_school.id) do %>
				<p><%= truncate(note.content, length: 40) %></p>
			<% end %>	
			<p class="noteCity"><%= "#{note.high_school.city}, #{note.high_school.state.abbreviation}"   %> </p>
			<h5>Taken on: <%= note.time_tag.in_time_zone(@user.time_zone).strftime("%m/%d/%y") %></h5 style="color: orange;">
			<br>
		<% end %>
	</div>
<% end %>	

app/views/notes/_search.html.erb
<div class="text-center">
	<br>
	<div id="hs-name-search">
		<%= text_field_tag "note[hs_name_query]",
				nil,
				id: "notes-hs-name-search",
				placeholder: 'SEARCH BY HIGH SCHOOL' %>
	</div>

	<div id="hs-keyword-search">
		<%= text_field_tag "note[hs_keyword_query]",
				nil,
				id: "notes-hs-keyword-search",
				placeholder: 'SEARCH BY KEYWORD' %>
	</div>

	<div id="search-button-container">
		<button type="submit" user-id="<%= @user.id %>" id="notes-keyword-search-button" class="btn">SEARCH</button>
	</div>

	<br><br><hr>

</div>

app/views/notes/all_notes.html.erb
<div class="container">
  <div class="col-md-12">
    <div class="col-md-12">
      <div class="col-md-12">
        <%= link_to ("&nbsp; <i class='fa fa-chevron-left'></i>&nbsp; Back").html_safe, :back, { :class=>"backBtn" } %>
      </div>
    </div>
  </div>
</div>

<div class="home-header">
  <h1>Notes</h1>
  <h2>Search and view your notes</h2>
</div>

<div class="index-notes-container">
  <div class="notes-search-container row">
    <%= render(partial: 'notes/search',locals: { user: @user }) %>
      <div class="notes-search-results col-md-12">
        <% if @notes.blank? %>
          <p>You do not have any notes.</p>
        <% else %>  
          <% @notes.each do |note| %>
            <div class="note-container">
            <%= link_to raw("<i class=\"glyphicon glyphicon-remove\"></i>"), 
                user_note_path(@user.id, note.id),
                method: :delete,
                data: { confirm: "Delete this note?" },
                remote: true,
                class: 'close' %>
            <%= link_to high_school_path(note.high_school.id) do %>
              <h2><%= note.high_school.name %></h2>
            <% end %>
            <p><%= "#{note.high_school.city}, #{note.high_school.state.abbreviation}"%> </p> | 
            <h5>Taken on: <%= note.time_tag.in_time_zone(@user.time_zone).strftime("%m/%d/%y") %></h5>
              <br>
              <p class="note-content"><%= note.content %></p>
              <%=form_for :note, url: user_high_school_note_path(current_user, note.high_school, note), action: :update, method: "PUT" do |f| %>  
              
                <%= f.text_area :content, value: note.content, class: "update-note", disabled: true %>
                <%= button_tag 'Save',  class: "update-note-button", disabled: true,  'data-disable-with' =>  "<i class='fa fa-spinner fa-spin'></i>".html_safe %>
                
              <% end %>
              <button class="edit-note-button">EDIT</button>
            </div>
            <hr><br>
          <% end %>  
        <% end %>  
      </div>
  </div>
  <%= will_paginate @notes %>
</div>	

app/views/notes/index.html.erb
<div class="container">
  <div class="col-md-12">
      <div class="col-md-12">
        <div class="col-md-12">
          <%= link_to ("&nbsp; <i class='fa fa-chevron-left'></i>&nbsp; Back").html_safe, :back, { :class=>"backBtn" } %>
        </div>
      </div>
  </div>
</div>

<div class="home-header">
  <h1>Notes</h1>
  <h2>Search and view your notes</h2>
</div>
<div class="index-notes-container">

  <div class="notes-search-container row">
    <%= render(partial: 'notes/search',locals: { user: @user }) %>

    <div class="notes-search-results col-md-12">
        <% if @notes.blank? %>
          <p>You do not have any notes.</p>
        <% else %>  
          <% @notes.each do |note| %>
            <div class="note-container">
            <%= link_to raw("<i class=\"glyphicon glyphicon-remove\"></i>"), 
                user_note_path(@user.id, note.id),
                method: :delete,
                data: { confirm: "Delete this note?" },
                remote: true,
                class: 'close' %>
            <%= link_to high_school_path(note.high_school.id) do %>
              <h2><%= note.high_school.name %></h2>
            <% end %>
            <p><%= "#{note.high_school.city}, #{note.high_school.state.abbreviation}"%> </p> | 
            <h5>Taken on: <%= note.time_tag.in_time_zone(@user.time_zone).strftime("%m/%d/%y") %></h5>
              <br>
              <p class="note-content"><%= note.content %></p>
              <%=form_for :note, url: user_high_school_note_path(current_user, note.high_school, note), action: :update, method: "PUT" do |f| %>  
              
                <%= f.text_area :content, value: note.content, class: "update-note", disabled: true %>
                <%= button_tag 'Save',  class: "update-note-button", disabled: true,  'data-disable-with' =>  "<i class='fa fa-spinner fa-spin'></i>".html_safe %>
                
              <% end %>
              <button class="edit-note-button">EDIT</button>
            </div>
            <hr><br>
          <% end %>  
        <% end %>  
      </div>

    <div class="col-md-12">
      <%= link_to "View all Notes", all_notes_user_high_schools_path(current_user.id), class: "viewNotes"%>
    </div>
  
  </div>
  
</div>	

app/views/notes/keyword_search.html.erb
<div class="container">
  <div class="col-md-12">
    <div class="col-md-12">
      <div class="col-md-12">
        <%= link_to ("&nbsp; <i class='fa fa-chevron-left'></i>&nbsp; Back").html_safe, :back, { :class=>"backBtn" } %>
      </div>
    </div>
  </div>
</div>

<div class="home-header">
  <h1>Notes</h1>
  <h2>Search and view your notes</h2>
</div>



<div class="index-notes-container">

  <div class="notes-search-container">
    <%= render(partial: 'notes/search',locals: { user: @user }) %>

      <div class="notes-search-results">

        <h2>Search Results:</h2><hr>
        <% unless @search %> 
          <p>No notes matched your search parameters. Please try again.</p>
        <% else %>    
          <% @search.each_hit_with_result do |hit, note| %>
            <% if hit.highlights(:high_school).length > 0 && hit.highlights(:content).length > 0 %>
              
              <%= link_to raw("<i class=\"glyphicon glyphicon-remove\"></i>"), 
                user_note_path(@user.id, note.id),
                method: :delete,
                data: { confirm: "Delete this note?" },
                remote: true,
                class: 'close' %>
          
              <%= link_to high_school_path(note.high_school.id) do %>
                <% hit.highlights(:high_school).each do |hit| %>
                  <h2><%= hit.format { |fragment| content_tag(:span, fragment, class: "highlighted-high_school") }.html_safe %></h2><br>
                <% end %>
              <% end %>
                <p><%= "#{note.high_school.city}, #{note.high_school.state.abbreviation}"   %> </p>
    
              <% hit.highlights(:content).each do |hit| %>
                <%= hit.format { |fragment| content_tag(:span, fragment, class: "highlighted-content") }.html_safe %>
              <% end %>  

              <br>   
            <% elsif hit.highlights(:high_school).length > 0 && hit.highlights(:content).blank? %>

              <%= link_to raw("<i class=\"glyphicon glyphicon-remove\"></i>"), 
                user_note_path(@user.id, note.id),
                method: :delete,
                data: { confirm: "Delete this note?" },
                remote: true,
                class: 'close' %>

              <%= link_to high_school_path(note.high_school.id) do %>
                <% hit.highlights(:high_school).each do |hit| %>
                  <h2><%= hit.format { |fragment| content_tag(:span, fragment, class: "highlighted-high_school") }.html_safe %></h2><br>
                <% end %>
              <% end %>  
                  <%= "#{note.high_school.city}, #{note.high_school.state.abbreviation}"   %> </p>
              
              <p> <%= hit.stored(:content)[0] %> </p>
              <br><hr>
            <% elsif hit.highlights(:high_school).blank? && hit.highlights(:content).length > 0 %>

              <%= link_to raw("<i class=\"glyphicon glyphicon-remove\"></i>"), 
                user_note_path(@user.id, note.id),
                  method: :delete,
                  data: { confirm: "Delete this note?" },
                  remote: true,
                  class: 'close' %>
              <%= link_to high_school_path(note.high_school.id) do %>
                <h2 class="unhighlighted-high-school"> <%= hit.stored(:high_school)[0] %> </h2> 
              <% end %>
                <p><%= "#{note.high_school.city}, #{note.high_school.state.abbreviation}"   %> </p>                  
               
                <% hit.highlights(:content).each do |hit| %>
                <%= hit.format { |fragment| content_tag(:span, fragment, class: "highlighted-content") }.html_safe %>
                <% end %>  
                <br><hr><br>
            <% end %>
          <% end %>
        <% end %> 

        <div class="col-md-12">
          <%= link_to "View all Notes", all_notes_user_high_schools_path(current_user.id), class: "viewNotes"%>
        </div><br><br>

      </div>
  </div>
</div>  