config/routes.rb
Rails.application.routes.draw do

  #404 PG
  match "/404", to: "errors#error404", via: :all

  #500 PG
  match '/500', to: 'errors#error500', via: :all

  #SITEMAP
  get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations" }, path_names: {sign_in: "login", sign_out: "logout"}
  
  as :user do
    patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  get 'help/help_contact'

  get 'help/about'

  get 'help/terms_privacy'

  put 'help/help_contact_form'

  namespace :reps do
    devise_for :users, controllers: { registrations: "rep_registrations" },
                                        path_names: {sign_in: "login", sign_out: "logout"},
                                        only: :registrations
  end 

  devise_scope :user do
    put 'checkout' => 'registrations#checkout' 
  end 

  resources :high_schools do
    collection do
      get 'high_school'
      put 'error'
      put 'missing'
      get 'search', path: 'search'
      get 'name_or_ceeb_query_auto_complete'
      get 'city_auto_complete'
      get 'get_counties'
    end
  end
  
  resources :prospective_students do
    collection do
      get "dashboard"
      put "get_prospective_students_by_year"
      get "export"
      put "get_prospective_students_by_id"
      get "send_mail"
      get "send_test_mail"
    end
  end

  resources :users do
    get 'visits_csv' => 'users#visits_csv'
    collection do
      get 'home'
    end 

    resources :high_schools do
      collection do
        get 'all_notes' => 'notes#all_notes'
        get 'keyword_search' => 'notes#keyword_search'
      end  
      resources :notes
    end    
    resources :preferred_phones, only: [:create, :update, :destroy]
    resources :preferred_guidance_websites, only: [:create, :update, :destroy]
    resources :preferred_calendars, only: [:create, :update, :destroy]
    resources :preferred_emails, only: [:create, :update, :destroy]
    resources :saved_searches,  only: [:index,  :create, :destroy]
    resources :visits do
      put 'jsDragUpdate', as: 'drag_update'
      put 'formUpdate', as: 'form_update'
      put 'update_confirmed' => 'visits#update_confirmed'
      collection do
        get 'calendar_feed'
        get 'agenda'
        put 'share'
      end    
    end  
    resources :notes
  end 

	root 'users#home'

  namespace :admin do	   
    resources :high_schools do
      collection do
        post 'import_for_new'
        post 'import_for_update'
        get 'export'
        get 'import_template'
        get 'dashboard'
        get 'search'
      end
    end  
  end

  resources :admin do
    collection do
      resources :admins, controller: 'admin/admins', except: [:show]
    end
  end    
  
  resources :admin do
    collection do
      resources :accounts, controller: 'admin/accounts'
    end  
  end    

  resources :institutions, only: [:none] do 
    collection do
      get 'institution_auto_complete'
      get 'institution'
    end
  end    

  resources :accounts do
    collection do
      get 'credit_card_form'
    end
  end
  
end

app/models/visit.rb
class Visit < ActiveRecord::Base

	require 'csv'
	belongs_to :user
	belongs_to :high_school

	include DateTimeAttribute

	date_time_attribute :start
	date_time_attribute :end

	validates_presence_of :title, 
		:location, 
		:start,
		:end,
		:time_zone

	validates :start, presence: true, date: { before_or_equal_to: :end, message: " time of an event cannot be after its end."} 

	validates :time_zone, 
	inclusion: { 
 		in: ActiveSupport::TimeZone.zones_map(&:name).keys, 
 		message: "is not a valid time zone"
	} 

	after_create { |visit| visit.addStartAndEndDateTimesOnCreate}

	def user_visit_start_dst_adjuster(user)
		if self.start.in_time_zone(user.time_zone).dst?
			(self.start - 1.hour).in_time_zone(user.time_zone)
		else
			self.start.in_time_zone(user.time_zone)
		end
	end	

	def user_visit_end_dst_adjuster(user)
		if self.end.in_time_zone(user.time_zone).dst?
			(self.end - 1.hour).in_time_zone(user.time_zone)
		else
			self.end.in_time_zone(user.time_zone)
		end
	end	

	def start_dst_adjuster
		if self.start.in_time_zone(self.time_zone).dst?
			(self.start - 1.hour).in_time_zone(self.time_zone)
		else
			self.start.in_time_zone(self.time_zone)
		end
	end

	def end_dst_adjuster
		if self.end.in_time_zone(self.time_zone).dst?
			(self.end - 1.hour).in_time_zone(self.time_zone)
		else
			self.end.in_time_zone(self.time_zone)
		end
	end

	def self.addStartAndEndDateTimesToAll
    Visit.find_each do |visit|
    	visit.update_attributes({
      	endDateTime: visit.end,
      	startDateTime: visit.start
      }) 
  	end
	end

	def addStartAndEndDateTimes(object)
		self.update_attributes(object)
		self.update_attributes({
    	endDateTime: self.end,
    	startDateTime: self.start
    })
    return true
	end

	def addStartAndEndDateTimesOnCreate
		self.update_attributes({
    	endDateTime: self.end,
    	startDateTime: self.start
    })
	end

	def textColor
		if self.category == "College Fair"
			return "#79c2df"
		elsif self.category =="Hotel"
			return "#363636"
		elsif self.category == "Reminder"
			return "#E66E00"
		elsif self.category == "High School Visit" && self.confirmed?
			return "#456f88" 
		elsif self.category == "High School Visit" && self.confirmed != true
			return "#B61F1F"
		else
			return "#615177"
		end
	end	

	def time_zone_mapping
    ActiveSupport::TimeZone::MAPPING[self.time_zone]
  end


end	

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  include VisitsHelper

  before_filter :authenticate_user! 

  before_filter :force_html, only: :index

	def index
    @user = User.find params[:user_id]
    @visits = @user.visits.includes(:high_school, user: [:preferred_phones])
    @new_visit = Visit.new
    respond_to do |format|
      format.json { render json: @visits, each_serializer: VisitSerializer }
      format.html { render "index", user: @user }
    end
  end

  def calendar_feed
    @user = User.find(params[:user_id])
    @visits = @user.visits
    respond_to do |format|
      format.ics
    end
  end  

  def share
    @user = current_user
    if valid_email?(params[:email])
      flash[:share_success] = "Your weekly agenda has been sent to #{params[:email]}"
      @user.send_share_weekly_agenda(params[:email])
    else
      flash[:share_error] = "Please enter a valid email address"
    end
    redirect_to user_visits_path(@user) 
  end
  
  def agenda
    @user = current_user
    @visits = @user.visits.where(start: (Time.now.midnight - 1.day)..Time.now + 7.days).order(created_at: :desc)
  end
 
  def edit
    @user = User.find(params[:user_id])
    @visit = Visit.find(params[:id])
    respond_to do |format|
      format.json { render json: @visit, serializer: VisitSerializer }
    end
  end

  def destroy
    @user = current_user
    @visit = @user.visits.find(params[:id])
    if @visit.destroy
      flash[:calendar] = "Your calendar event "+'"'+"#{@visit.title}"+'"' + " has been deleted."
      respond_to do |format|
        format.js {render inline: "location.reload();" }
      end
    else  
      flash[:calendar] = "There was a problem deleting #{@visit.title}, please try again."
    end
  end
 
  def create
    @user = User.find(params[:user_id])
    @visit = @user.visits.new(visit_attrs(visit_params))
    @visits = @user.visits
    (@visit.confirmed = params[:commit] == "Save as Confirmed" ?  true : false) if params[:commit]
    if @visit.save
      flash[:calendar_success] = "Your calendar event #{@visit.title} has been added to your calendar."
      respond_to do |format|
        format.js {render inline: "location.reload();" }
      end
    else
      flash[:calendar_errors] = @visit.errors.full_messages
      respond_to do |format|
        format.js { render inline: "location.reload();" }
      end
    end
  end

  def jsDragUpdate
    @user = User.find(params[:user_id])
    @visit = @user.visits.find(params[:visit_id])
    if @visit.addStartAndEndDateTimes(visit_drag_attrs(visit_params))
      @visits = @user.visits
      respond_to do |format|
        format.json { render json: @visits, each_serializer: VisitSerializer }
        format.html { redirect_to action: "index", id: @user.id }
      end
    else
      flash.alert = @visit.errors.full_messages.to_sentence
      redirect_to "index", user: @user, visit: @visit
    end 
  end   
    
  def formUpdate  
    @user = User.find(params[:user_id])
    @visit = @user.visits.find(params[:visit_id])
    if @visit.addStartAndEndDateTimes(visit_attrs(visit_params)) && @visit.errors.blank?

      @visits = @user.visits
      flash[:calendar_update] = "Your calendar event #{@visit.title} has been updated."
      respond_to do |format|
        format.json { render json: @visits, each_serializer: VisitSerializer }
        format.html { redirect_to action: "index" }
      end
    elsif @visit.errors
      flash[:calendar_update_errors] = @visit.errors.full_messages
      respond_to do |format|
        format.json { render json: @visits, each_serializer: VisitSerializer }
        format.html { redirect_to action: "index" }
      end
    else
      flash[:calendar_update] = "Your calendar event #{@visit.title} has been updated."
      redirect_to "index", user: @user, visit: @visit
    end
  end

  def update_confirmed
    @visit = Visit.find params[:visit_id]
    if @visit.update_attributes({ confirmed: params[:confirmed]})
      flash[:calendar_success] = "Your calendar event #{@visit.title} has been updated."
      respond_to do |format|
        format.js {render inline: "location.reload();" }
      end
    else
      flash[:calendar_errors] = "Something went wrong. Please try again."
      respond_to do |format|
        format.js { render inline: "location.reload();" }
      end
    end
  end  

	private

  def valid_email?(email)
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    email.present? && (email =~ email_regex)
  end

	def visit_params
    params.require(:visit).permit(:title, :location, :description, :category, :start, :end, :start_date_raw, 'start_time_raw(4i)', 'start_time_raw(5i)', :end_time_raw, :end_date_raw, 'end_time_raw(4i)', 'end_time_raw(5i)', :end_time_raw, :end_date, :end_time, :user_id, :time_zone, :contact, :id, :user_id, :high_school_id, :confirmed)
  end

  def visit_start
    startDate = DateTime.strptime(params[:visit][:start_date_raw]+" #{params[:visit]['start_time_raw(4i)']}:#{params[:visit]['start_time_raw(5i)']}:00 " + params[:visit]["time_zone"], "%m-%d-%Y %H:%M:%S %Z")
  end

  def visit_end
    endDate = DateTime.strptime(params[:visit][:end_date_raw]+" #{params[:visit]['end_time_raw(4i)']}:#{params[:visit]['end_time_raw(5i)']}:00 " + params[:visit]["time_zone"], "%m-%d-%Y %H:%M:%S %Z")
  end

  def visit_attrs(visit_params)
    visit_attrs = visit_params.clone
    visit_attrs[:start] = visit_start
    visit_attrs.delete :start_date_raw
    visit_attrs.delete 'start_time_raw(4i)'
    visit_attrs.delete 'start_time_raw(5i)'

    visit_attrs[:end] = visit_end
    visit_attrs.delete :end_date_raw
    visit_attrs.delete 'end_time_raw(4i)'
    visit_attrs.delete 'end_time_raw(5i)'
    
    return visit_attrs
  end 

  def visit_drag_attrs(visit_params)
    visit_drag_attrs = visit_params.clone
    visit_drag_attrs[:start] = DateTime.strptime(visit_drag_attrs[:start]).in_time_zone(visit_drag_attrs[:time_zone])
    visit_drag_attrs[:end] = DateTime.strptime(visit_drag_attrs[:end]).in_time_zone(visit_drag_attrs[:time_zone])
    visit_drag_attrs[:time_zone] = time_zone_converter_for_ics(visit_drag_attrs[:time_zone])
    return visit_drag_attrs

  end


end

app/helpers/visits_helper.rb
module VisitsHelper 	

	def time_zone_converter_for_ics(tz_string_from_form)
		ics_tz = Hash.new
		case tz_string_from_form
		when "Pacific/Honolulu"
			ics_tz = "Hawaii" 
		when "America/Juneau"	
			ics_tz = "Alaska" 
		when "America/Los_Angeles"
			ics_tz = "Pacific Time (US & Canada)" 
		when "America/Phoenix"	
			ics_tz = "Arizona" 
		when "America/Denver"			
			ics_tz = "Mountain Time (US & Canada)" 
		when "America/Chicago"
			ics_tz = "Central Time (US & Canada)" 
		when "America/Indianapolis"
			ics_tz = "Indiana (US & Canada)" 
		when "America/New_York"
			ics_tz = "Eastern Time (US & Canada)" 
		end
		return ics_tz	
	end

	def time_zone_converter(time_zone_string)
		case time_zone_string
		when "Hawaii" 
			return "Pacific/Honolulu"
		when "Alaska" 
			return "America/Juneau"	
		when "Pacific Time (US & Canada)" 
			return "America/Los_Angeles"
		when "Arizona" 
			return "America/Phoenix"	
		when "Mountain Time (US & Canada)" 
			return "America/Denver"			
		when "Central Time (US & Canada)" 
			return "America/Chicago"
		when "Indiana (US & Canada)" 
			return "America/Indianapolis"
		when "Eastern Time (US & Canada)" 
			return "America/New_York"
		end
	end	

end

app/views/visits/_agenda.html.erb
<div class="visible-sm visible-xs">
	<% @visits.each do |visit| %>		
		<% confirmed = visit.confirmed? ? 'confirmed' : 'tentative' %>
		<% if visit.high_school %>
			<%= link_to high_school_path(visit.high_school.id) do %>
				<span class='schoolName <%= "#{confirmed} #{visit.category.downcase.gsub(" ", "-")}" %>' >
					<%= truncate( visit.title, length: 50 ) %>
				</span>	
			<% end %>
		<% else %>
			<span class='schoolName <%= "#{confirmed} #{visit.category.downcase.gsub(" ", "-")}" %>'>
				<%= truncate( visit.title, length: 50 ) %>
			</span>	
		<% end %>

		<div class="tableContainer">
			<div class="tableCell">
				<i class='<%=" #{confirmed} #{visit.category.downcase.gsub(" ", "-")}"%> glyphicon glyphicon-calendar'></i>
			</div>
			<div class="tableCell">
				<span class="grey">
					<%= visit.user_visit_start_dst_adjuster(@user).strftime("%m/%d")%> - <%= visit.user_visit_end_dst_adjuster(@user).strftime("%m/%d")%>
				</span>
			</div>
		</div>

		<div class="tableContainer">
			<div class="tableCell">
				<i class='<%=" #{confirmed} #{visit.category.downcase.gsub(" ", "-")}"%> glyphicon glyphicon-time'></i>
			</div>
			<div class="tableCell">
				<span class="grey">
					<%= visit.user_visit_start_dst_adjuster(@user).strftime("%I:%M %p") %> - <%= visit.user_visit_end_dst_adjuster(@user).strftime("%I:%M %p") %>
				</span>
			</div>
		</div>

		<div class="tableContainer">
			<div class="tableCell">
				<i class='<%=" #{confirmed} #{visit.category.downcase.gsub(" ", "-")}"%> glyphicon glyphicon-info-sign'></i>
			</div>
			<div class="tableCell">
				<span class="grey">
					<%=visit.category%>
				</span>
			</div>
		</div>



		<div class="tableContainer">
			<div class="tableCell">
				<i class='<%="#{confirmed} #{visit.category.downcase.gsub(" ", "-")}"%> glyphicon glyphicon-map-marker'></i>
			</div>
			<div class="tableCell">
				<span class="grey">
					<% if mobile_device? %>
						<a target='_blank' href='<%="maps:q=#{visit.location}"%>'>
							<%=visit.location%>
						</a>
					<% else %>
						<a target='_blank' href='<%="http://maps.google.com/maps?q=#{visit.location}"%>'>
							<%=visit.location%>
						</a>
					<% end %>
				</span>
			</div>
		</div>
		
		<% if visit.high_school	%>
		
			<div class="tableContainer">
				<div class="tableCell">
					<i class='<%="#{confirmed} #{visit.category.downcase.gsub(" ", "-")}"%> glyphicon glyphicon-phone-alt'></i> 
				</div>
				
				<div class="tableCell">
					<% unless user.preferred_phones.where(high_school: visit.high_school).empty? %>
						<span class="grey">
							<%= user.preferred_phones.where(high_school: visit.high_school).first.num %>
						</span>
					<% else %>
						<span class="grey">
							<%= visit.high_school.guidance_phone_num || visit.high_school.hs_phone_num || "n/a" %>
						</span>
					<% end %>
				</div>
			</div>


			<div class="tableContainer">
				<div class="tableCell">
					<i class='<%=" #{confirmed} #{visit.category.downcase.gsub(" ", "-")}"%> glyphicon glyphicon-envelope'></i>
				</div>

				<div class="tableCell">
					<span class="grey">
						<div class="preferred-emails-message">
							<%= render(partial: 'preferred_emails/messages',locals: {message: @preferred_email}) %>
						</div>
						<a class="add-preferred-email-from-dashboard" type="button" data-hs-id="<%=visit.high_school.id%>"> Add an Email Contact</a>
						<%= form_for [user, @preferred_email], html: {class: "add-preferred-email-from-dashboard hidden"},remote: true do |f| %>
							
							<%= f.text_field :address, 
									{ placeholder: 'Add an email...',
									id: "preferred_email_text-field" } %>	
							<%= f.hidden_field :high_school_id, value: visit.high_school.id %>
							<%= f.hidden_field :user_id, value: user.id %>
							<div class="button-container">
								<%= f.submit "SAVE", { class: "button save" }	%>
							</div>	
						<% end %>	
					</span>
				</div>
			</div>


			<div class="tableContainer">
				<div class="tableCell">
					<i class='<%=" #{confirmed} #{visit.category.downcase.gsub(" ", "-")}"%> glyphicon glyphicon-pencil'></i>
				</div>

				<div class="tableCell">
					<span class="grey">
						<%# link_to high_school_path(visit.high_school.id) do %>
							<!-- Add a note -->
						<%# end %>
						<a class="add-note-from-dashboard" type="button" data-hs-id="<%=visit.high_school.id%>"> Add a Note</a>
						<%= form_for [user, @note], html: {class: "add-note-from-dashboard hidden"},remote: true do |f| %>
							<div class="notes-message">
								<%= render(partial: 'notes/messages',locals: {message: @message}) %>
							</div>
							<%= f.text_area :content, 
									{ placeholder: 'Take notes here...',
									id: "note_content-field" } %>	
							<%= f.hidden_field :high_school_id, value: visit.high_school.id %>
							<%= f.hidden_field :user_id, value: user.id %>
							<div class="button-container">
								<%= f.submit "SAVE", { class: "button save" }	%>
							</div>	
						<% end %>	
					</span>
				</div>
			</div>

			
			
		<%end%>			
		<hr>
	<% end %>
</div>	

<div class="visible-lg visible-md">
	<% @visits.each do |visit| %>
	<div id="dashboard-visit">
		<div class="visit-date"><%= visit.user_visit_start_dst_adjuster(@user).strftime("%m/%d") %></div>
		<div class="visit-description- <%=visit.category.downcase.gsub(" ", "-")%>">
			<p class="visit-description" id="dashboard-visit">
				<% if visit.high_school %>
					<%= link_to high_school_path(visit.high_school.id) do %>	
						<%= truncate( visit.title, length: 50 ) %>
					<% end %><br/>
				<% else %>
				
					<%= link_to user_visits_path(current_user.id) do %>	
						<%= truncate( visit.title, length: 50 ) %>
					<% end %><br/>
				<% end %>	
				<%= visit.category %>
			</p>
		</div>
	</div>
	<% end %>	
</div>

app/views/visits/_calendar.html.erb
<div class="container">
	<%= link_to ("&nbsp; <i class='fa fa-chevron-left'></i>&nbsp; Back").html_safe, :back, { :class=>"backBtn" } %>
</div>

<div id="calendar-header">
	<h1>Calendar</h1>
</div>



<div id="calendar-container" class="container col-md-12">

  <% if flash && flash[:calendar_errors] %>
    <% flash[:calendar_errors].each do |msg| %>
      <div class="webflash alert calendar_update_errors">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p>Unable to create your visit. <%=msg%></p>
      </div>
    <% end %>  
  <% elsif flash[:calendar_success] %>
    <div class="webflash calendar-success">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <p><%=flash[:calendar_success]%></p>
    </div>
	<% end %>

	<% if flash && flash[:calendar_update]%>
	  <div class="webflash alert calendar-update">
	    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	    <p><%= flash[:calendar_update] %></p>
	  </div>
	<% end %>

	<% if flash && flash[:calendar_update_errors] %>
	  <% flash[:calendar_update_errors].each do |msg| %>
	    <div class="webflash alert calendar_update_errors">
	    	<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
	      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	      <p>Unable to update your visit. <%=msg%></p>
	    </div>
	  <% end %>  
	<% end %>

	<div class="userTimeZone">
	  <span class="timezone-display-1">Calendar is displaying: <%= collection_select :user, :time_zone, ActiveSupport::TimeZone.us_zones, :name, :to_s, selected: @user.time_zone || "Eastern Time (US & Canada)", remote: true %></span>
	</div>
	<div class="dropdown">
	  <button id="dLabel" class="hidden-sm hidden-xs" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    Options
	    <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
			
			<li data-toggle="modal" data-target="#newVisitModal"><a type="button">Add a New Event</a></li>
			
			<li data-toggle="modal" data-target="#syncCalendarModal"><a type="button">Sync to Calendar</a></li>


			<li data-toggle="modal" data-target="#shareAgendaModal"><a type="button">Share Weekly Agenda</a></li>

			<li><%= link_to "Download Visits .CSV", "/users/#{@user.id}/visits_csv.csv" if @user.visits.present? %></li>
			
	  </ul>
	  	<div class="hidden-lg hidden-md mobileCalBtns">
	  	<a type="button" data-toggle="modal" data-target="#newVisitModal">New Event</a>
			<a type="button" data-toggle="modal" data-target="#syncCalendarModal">Sync Calendar</a>
			<a type="button" data-toggle="modal" data-target="#shareAgendaModal">Share Agenda</a>
		</div>
	</div>


	<div id="calendar" user=<%=user.id%> >
		<div class="keys col-md-12">
			<ul>
				<li id="key">Key</li>
				<li id="confirmed-high-school-visit">Confirmed HS Visit</li>
				<li id="tentative-high-school-visit">Tentative HS Visit</li>
				<li id="college-fair">College Fair</li>
				<li id="hotel">Hotel</li>
				<li id="reminder">Reminder</li>
				<li id="other">Other</li>
			</ul>
		</div>
	</div>	

</div>











		

app/views/visits/_calendar_sync_menu.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="editVisitModalLabel">Sync with your calendar</h4>
</div>

<div class="modal-body">        
  <div class="calendar-sync-container">
    <ul>
      <li><a id="google-tab" href="#google">Google Calendar</a></li>
      <li><a id="other-tab" href="#other">iCal, Outlook, and Other</a></li>
    </ul>

    <div id="google">
      <%= render(partial: "visits/sync/google", locals: { user: @user } ) %>
    </div>

    <div id="other">
      <%= render(partial: "visits/sync/other", locals: { user: @user } ) %>
    </div>
  </div>  
</div>

app/views/visits/_share_agenda.html.erb
<% if @user.id %>  
  <%=form_tag( share_user_visits_path(@user) , method: :put ) do %>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="shareAgendaModal">Share Your Weekly Agenda</h3>
    </div>

    <div class="modal-body">
      <p>Enter an email address with whom you want to share your agenda</p>
      <%= text_field_tag 'email', nil, placeholder: "Enter Email Address of Recipient" %>
    </div>

    <div class="modal-footer">
     <button class="btn btn-primary">Share Agenda</button>
    </div>
  <% end %> 
<% end %>  

app/views/visits/calendar_feed.ics.erb
BEGIN:VCALENDAR
PRODID:-//RepsEdge//V+V 2015//EN 
VERSION:2.0
METHOD:PUBLISH
CALSCALE:GERGORIAN
X-WR-CALNAME:RepsEdge
<% @visits.each do |visit| %>
BEGIN:VEVENT
CLASS:PUBLIC
UID:<%=visit.id%>@repsedge.com
DTSTART:<%=visit.user_visit_start_dst_adjuster(@user).strftime("%Y%m%dT%H%M%S")%>
DTEND:<%=visit.user_visit_end_dst_adjuster(@user).strftime("%Y%m%dT%H%M%S")%>
DTSTAMP:<%=Time.now.strftime("%Y%m%dT%H%M%S")%>
DESCRIPTION: <%= visit.description%>
LOCATION: <% visit.location %>
SUMMARY: <%= visit.title %>
TRANSP:TRANSPARENT
END:VEVENT
<% end %>
END:VCALENDAR

app/views/visits/index.html.erb
<%= render(partial: 'visits/calendar',locals: { user: @user, visits: @visits, visit: @visit }) %>